[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run migrate && npm start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.env]
NODE_ENV = "production"

# Secrets and environment variables
# Make sure to set these in Railway's dashboard
# - SESSION_SECRET: Used for secure session management

# PostgreSQL Database Configuration
# The DATABASE_URL will be automatically injected by Railway
# when you link a PostgreSQL service to this project

# File System and Static Assets
# Railway provides an ephemeral filesystem, which means
# any files written during runtime will not persist after restarts
# Use external storage services for persistent file storage if needed
