[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[phases.setup]
aptPkgs = ["openssl", "ca-certificates"]

[phases.migrate]
cmds = ["tsx server/migrate.ts"]

[[services]]
name = "web"
port = 5000
internal = false