[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "NODE_ENV=production node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.env]
NODE_ENV = "production"
PORT = "5000"

[[ports]]
port = "5000"