[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.env]
NODE_ENV = "production"
PORT = "5000"

[[ports]]
port = "5000"