name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check TypeScript
      run: npm run check
      
    - name: Generate Migrations
      run: npm run generate
      
    - name: Build application
      run: npm run build
      
    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp -r dist deploy/
        cp -r migrations deploy/
        cp -r .ebextensions deploy/
        cp package.json package-lock.json deploy/
        cd deploy && zip -r ../deploy.zip .
      
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: kitcho-family
        environment_name: kitcho-family-production
        version_label: kitcho-family-${{ github.sha }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
        wait_for_environment_recovery: 300