name: Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Run tests
        run: npm test || true
        
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          
      - name: Verify deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          RAILWAY_URL=$(railway variables get RAILWAY_PUBLIC_URL || railway variables get RAILWAY_STATIC_URL)
          curl -f "$RAILWAY_URL/healthz" || exit 1
          echo "Deployment verified successfully!"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}